t=[
"Fantasia",
"Ficção científica",
"Distopia",
"Ação e aventura",
"Ficção Policial",
"Horror",
"Thriller e Suspense",
"Ficção histórica",
"Romance",
"Ficção Feminina",
"LGBTQ+",
"Ficção Contemporânea",
"Realismo mágico",
"Graphic Novel",
"Conto",
"Young adult – Jovem adulto",
"New adult – Novo Adulto ",
"Infantil",
]